### ISSUE TITLE
slime stacktraces broken w/ clojure-1.3 snapshots with pst

### ISSUE THREAD

**Issue by arohner** [technomancy/swank-clojure#21]
When running swank-clojure with a clojure 1.3 snapshot that includes clojure.repl/pst, exception handling is broken. 

Causing swank to evaluate a form that throws an exception does not bring up an sldb window with the stacktrace. slime-load-file (C-c C-l) and eval'ing forms in a slime repl demonstrate the behavior.

**Comment by technomancy** [comment]
I think this has been fixed with drewr's recent patch.

**Comment by arohner** [comment]
I'm still seeing this with clojure 1.3 alpha2 and a swank-clojure master built from source today.

**Comment by technomancy** [comment]
I believe this has been fixed; feel free to reopen if not.
